# Job to submit a Ray program from a pod outside a running Ray cluster.
apiVersion: batch/v1
kind: Job
metadata:
  generateName: ray-train-pytorch-huggingface-clothing-
  namespace: ray-cluster
spec:
  template:
    spec:
      serviceAccountName: ray-cluster-sa
      restartPolicy: Never
      containers:
        - name: hface
          image: $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ray-demo:latest
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "python /opt/train_pytorch_huggingface_clothing.py"
          resources:
            requests:
              cpu: 1000m
              memory: 6Gi
          env:
            - name: S3_BUCKET
              value: $S3_BUCKET
