apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${pvc_name}
  namespace: ${namespace}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ${storage_class_name} # Leave this blank otherwise it will complain about incorrect storage class
  resources:
    requests:
      storage: ${request_storage}
  volumeName: ${pv_name}
