apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-prometheus-stack-ray-monitor
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
    ray.io/node-type: head
spec:
  namespaceSelector:
    matchNames:
      - ${namespace}
  selector:
    matchLabels:
      ray.io/node-type: head
  endpoints:
    - port: metrics
